manifest-version = 1

[component]
name = "Amazon S3"
version = "0.2.2"
category = "data-collection"
subcategory = "warehouse"
wit-world-version = "0.4.0"
documentation = "https://github.com/edgee-cloud/amazon-s3-component/"
repository = "https://github.com/edgee-cloud/amazon-s3-component/"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud) and [Amazon S3](https://aws.amazon.com/s3/),
allowing you to collect and forward analytics events to your data lake on S3. 

All S3 objects are created under `{bucket}/{prefix}{random-key}.json` and contain a full JSON dump of the incoming event.
'''

[component.build]
command = "cargo build --target wasm32-wasip2 --release && cp ./target/wasm32-wasip2/release/s3_component.wasm s3.wasm"
output_path = "s3.wasm"

[component.settings.aws_access_key]
title = "Your AWS Access Key"
type = "string"
required = true

[component.settings.aws_secret_key]
title = "Your AWS Secret Access Key"
type = "string"
required = true

[component.settings.aws_session_token]
title = "Your AWS Session Token (optional)"
type = "string"
description = "Useful for tests, not recommended in production because it's short-lived"

[component.settings.aws_region]
title = "Your AWS Region"
type = "string"
required = true

[component.settings.s3_bucket]
title = "Your bucket name"
type = "string"
required = true

[component.settings.s3_key_prefix]
title = "Your key prefix (optional)"
type = "string"
description = "It will be used as key prefix for all S3 objects"
